blank_issues_enabled: false
contact_links:
  - name: Suggestions
    about: Create or add to suggestions for the server.
    url: https://github.com/Stardust-Labs-MC/StardustMC/discussions
  - name: Discord
    about: Get support, ask questions, and hang out on our Discord Server.
    url: https://discord.gg/stardustlabs
  - name: Wiki
    about: Useful information about StardustMC.
    url: https://github.com/Stardust-Labs-MC/StardustMC/wiki
